//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DietJournal.Web.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DietjournalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DietjournalEntities object using the connection string found in the 'DietjournalEntities' section of the application configuration file.
        /// </summary>
        public DietjournalEntities() : base("name=DietjournalEntities", "DietjournalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DietjournalEntities object.
        /// </summary>
        public DietjournalEntities(string connectionString) : base(connectionString, "DietjournalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DietjournalEntities object.
        /// </summary>
        public DietjournalEntities(EntityConnection connection) : base(connection, "DietjournalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BloodPressureEntry> BloodPressureEntries
        {
            get
            {
                if ((_BloodPressureEntries == null))
                {
                    _BloodPressureEntries = base.CreateObjectSet<BloodPressureEntry>("BloodPressureEntries");
                }
                return _BloodPressureEntries;
            }
        }
        private ObjectSet<BloodPressureEntry> _BloodPressureEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExerciseEntry> ExerciseEntries
        {
            get
            {
                if ((_ExerciseEntries == null))
                {
                    _ExerciseEntries = base.CreateObjectSet<ExerciseEntry>("ExerciseEntries");
                }
                return _ExerciseEntries;
            }
        }
        private ObjectSet<ExerciseEntry> _ExerciseEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodEntry> FoodEntries
        {
            get
            {
                if ((_FoodEntries == null))
                {
                    _FoodEntries = base.CreateObjectSet<FoodEntry>("FoodEntries");
                }
                return _FoodEntries;
            }
        }
        private ObjectSet<FoodEntry> _FoodEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SupplementEntry> SupplementEntries
        {
            get
            {
                if ((_SupplementEntries == null))
                {
                    _SupplementEntries = base.CreateObjectSet<SupplementEntry>("SupplementEntries");
                }
                return _SupplementEntries;
            }
        }
        private ObjectSet<SupplementEntry> _SupplementEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WaterEntry> WaterEntries
        {
            get
            {
                if ((_WaterEntries == null))
                {
                    _WaterEntries = base.CreateObjectSet<WaterEntry>("WaterEntries");
                }
                return _WaterEntries;
            }
        }
        private ObjectSet<WaterEntry> _WaterEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WeightEntry> WeightEntries
        {
            get
            {
                if ((_WeightEntries == null))
                {
                    _WeightEntries = base.CreateObjectSet<WeightEntry>("WeightEntries");
                }
                return _WeightEntries;
            }
        }
        private ObjectSet<WeightEntry> _WeightEntries;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BloodPressureEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBloodPressureEntries(BloodPressureEntry bloodPressureEntry)
        {
            base.AddObject("BloodPressureEntries", bloodPressureEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExerciseEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExerciseEntries(ExerciseEntry exerciseEntry)
        {
            base.AddObject("ExerciseEntries", exerciseEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodEntries(FoodEntry foodEntry)
        {
            base.AddObject("FoodEntries", foodEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SupplementEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSupplementEntries(SupplementEntry supplementEntry)
        {
            base.AddObject("SupplementEntries", supplementEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WaterEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWaterEntries(WaterEntry waterEntry)
        {
            base.AddObject("WaterEntries", waterEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WeightEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeightEntries(WeightEntry weightEntry)
        {
            base.AddObject("WeightEntries", weightEntry);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DietJournal.Data.Entries", Name="BloodPressureEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BloodPressureEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BloodPressureEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="systolic">Initial value of the Systolic property.</param>
        /// <param name="diastolic">Initial value of the Diastolic property.</param>
        /// <param name="hearttRate">Initial value of the HearttRate property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="savedDate">Initial value of the SavedDate property.</param>
        public static BloodPressureEntry CreateBloodPressureEntry(global::System.Int32 id, global::System.Guid userId, global::System.Int32 systolic, global::System.Int32 diastolic, global::System.Int32 hearttRate, global::System.DateTime entryDate, global::System.DateTime savedDate)
        {
            BloodPressureEntry bloodPressureEntry = new BloodPressureEntry();
            bloodPressureEntry.Id = id;
            bloodPressureEntry.UserId = userId;
            bloodPressureEntry.Systolic = systolic;
            bloodPressureEntry.Diastolic = diastolic;
            bloodPressureEntry.HearttRate = hearttRate;
            bloodPressureEntry.EntryDate = entryDate;
            bloodPressureEntry.SavedDate = savedDate;
            return bloodPressureEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Systolic
        {
            get
            {
                return _Systolic;
            }
            set
            {
                OnSystolicChanging(value);
                ReportPropertyChanging("Systolic");
                _Systolic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Systolic");
                OnSystolicChanged();
            }
        }
        private global::System.Int32 _Systolic;
        partial void OnSystolicChanging(global::System.Int32 value);
        partial void OnSystolicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Diastolic
        {
            get
            {
                return _Diastolic;
            }
            set
            {
                OnDiastolicChanging(value);
                ReportPropertyChanging("Diastolic");
                _Diastolic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diastolic");
                OnDiastolicChanged();
            }
        }
        private global::System.Int32 _Diastolic;
        partial void OnDiastolicChanging(global::System.Int32 value);
        partial void OnDiastolicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HearttRate
        {
            get
            {
                return _HearttRate;
            }
            set
            {
                OnHearttRateChanging(value);
                ReportPropertyChanging("HearttRate");
                _HearttRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HearttRate");
                OnHearttRateChanged();
            }
        }
        private global::System.Int32 _HearttRate;
        partial void OnHearttRateChanging(global::System.Int32 value);
        partial void OnHearttRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SavedDate
        {
            get
            {
                return _SavedDate;
            }
            set
            {
                OnSavedDateChanging(value);
                ReportPropertyChanging("SavedDate");
                _SavedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavedDate");
                OnSavedDateChanged();
            }
        }
        private global::System.DateTime _SavedDate;
        partial void OnSavedDateChanging(global::System.DateTime value);
        partial void OnSavedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DietJournal.Data.Entries", Name="ExerciseEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExerciseEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExerciseEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="savedDate">Initial value of the SavedDate property.</param>
        public static ExerciseEntry CreateExerciseEntry(global::System.Int32 id, global::System.Guid userId, global::System.Int32 type, global::System.String description, global::System.DateTime entryDate, global::System.DateTime savedDate)
        {
            ExerciseEntry exerciseEntry = new ExerciseEntry();
            exerciseEntry.Id = id;
            exerciseEntry.UserId = userId;
            exerciseEntry.Type = type;
            exerciseEntry.Description = description;
            exerciseEntry.EntryDate = entryDate;
            exerciseEntry.SavedDate = savedDate;
            return exerciseEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Calories
        {
            get
            {
                return _Calories;
            }
            set
            {
                OnCaloriesChanging(value);
                ReportPropertyChanging("Calories");
                _Calories = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Calories");
                OnCaloriesChanged();
            }
        }
        private Nullable<global::System.Decimal> _Calories;
        partial void OnCaloriesChanging(Nullable<global::System.Decimal> value);
        partial void OnCaloriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SavedDate
        {
            get
            {
                return _SavedDate;
            }
            set
            {
                OnSavedDateChanging(value);
                ReportPropertyChanging("SavedDate");
                _SavedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavedDate");
                OnSavedDateChanged();
            }
        }
        private global::System.DateTime _SavedDate;
        partial void OnSavedDateChanging(global::System.DateTime value);
        partial void OnSavedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DietJournal.Data.Entries", Name="FoodEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="savedDate">Initial value of the SavedDate property.</param>
        public static FoodEntry CreateFoodEntry(global::System.Int32 id, global::System.Guid userId, global::System.String title, global::System.DateTime entryDate, global::System.DateTime savedDate)
        {
            FoodEntry foodEntry = new FoodEntry();
            foodEntry.Id = id;
            foodEntry.UserId = userId;
            foodEntry.Title = title;
            foodEntry.EntryDate = entryDate;
            foodEntry.SavedDate = savedDate;
            return foodEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        protected global::System.Int32 Meal
        {
            get
            {
                return _Meal;
            }
            set
            {
                OnMealChanging(value);
                ReportPropertyChanging("Meal");
                _Meal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Meal");
                OnMealChanged();
            }
        }
        private global::System.Int32 _Meal;
        partial void OnMealChanging(global::System.Int32 value);
        partial void OnMealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Calories
        {
            get
            {
                return _Calories;
            }
            set
            {
                OnCaloriesChanging(value);
                ReportPropertyChanging("Calories");
                _Calories = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Calories");
                OnCaloriesChanged();
            }
        }
        private Nullable<global::System.Decimal> _Calories;
        partial void OnCaloriesChanging(Nullable<global::System.Decimal> value);
        partial void OnCaloriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Carbs
        {
            get
            {
                return _Carbs;
            }
            set
            {
                OnCarbsChanging(value);
                ReportPropertyChanging("Carbs");
                _Carbs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Carbs");
                OnCarbsChanged();
            }
        }
        private Nullable<global::System.Decimal> _Carbs;
        partial void OnCarbsChanging(Nullable<global::System.Decimal> value);
        partial void OnCarbsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Fat
        {
            get
            {
                return _Fat;
            }
            set
            {
                OnFatChanging(value);
                ReportPropertyChanging("Fat");
                _Fat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fat");
                OnFatChanged();
            }
        }
        private Nullable<global::System.Decimal> _Fat;
        partial void OnFatChanging(Nullable<global::System.Decimal> value);
        partial void OnFatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Protein
        {
            get
            {
                return _Protein;
            }
            set
            {
                OnProteinChanging(value);
                ReportPropertyChanging("Protein");
                _Protein = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Protein");
                OnProteinChanged();
            }
        }
        private Nullable<global::System.Decimal> _Protein;
        partial void OnProteinChanging(Nullable<global::System.Decimal> value);
        partial void OnProteinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SavedDate
        {
            get
            {
                return _SavedDate;
            }
            set
            {
                OnSavedDateChanging(value);
                ReportPropertyChanging("SavedDate");
                _SavedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavedDate");
                OnSavedDateChanged();
            }
        }
        private global::System.DateTime _SavedDate;
        partial void OnSavedDateChanging(global::System.DateTime value);
        partial void OnSavedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DietJournal.Data.Entries", Name="SupplementEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SupplementEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SupplementEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="miligrams">Initial value of the Miligrams property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="savedDate">Initial value of the SavedDate property.</param>
        public static SupplementEntry CreateSupplementEntry(global::System.Int32 id, global::System.Guid userId, global::System.String description, global::System.Decimal miligrams, global::System.DateTime entryDate, global::System.DateTime savedDate)
        {
            SupplementEntry supplementEntry = new SupplementEntry();
            supplementEntry.Id = id;
            supplementEntry.UserId = userId;
            supplementEntry.Description = description;
            supplementEntry.Miligrams = miligrams;
            supplementEntry.EntryDate = entryDate;
            supplementEntry.SavedDate = savedDate;
            return supplementEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Miligrams
        {
            get
            {
                return _Miligrams;
            }
            set
            {
                OnMiligramsChanging(value);
                ReportPropertyChanging("Miligrams");
                _Miligrams = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Miligrams");
                OnMiligramsChanged();
            }
        }
        private global::System.Decimal _Miligrams;
        partial void OnMiligramsChanging(global::System.Decimal value);
        partial void OnMiligramsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SavedDate
        {
            get
            {
                return _SavedDate;
            }
            set
            {
                OnSavedDateChanging(value);
                ReportPropertyChanging("SavedDate");
                _SavedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavedDate");
                OnSavedDateChanged();
            }
        }
        private global::System.DateTime _SavedDate;
        partial void OnSavedDateChanging(global::System.DateTime value);
        partial void OnSavedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DietJournal.Data.Entries", Name="WaterEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WaterEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WaterEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="ounces">Initial value of the Ounces property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="savedDate">Initial value of the SavedDate property.</param>
        public static WaterEntry CreateWaterEntry(global::System.Int32 id, global::System.Guid userId, global::System.Decimal ounces, global::System.DateTime entryDate, global::System.DateTime savedDate)
        {
            WaterEntry waterEntry = new WaterEntry();
            waterEntry.Id = id;
            waterEntry.UserId = userId;
            waterEntry.Ounces = ounces;
            waterEntry.EntryDate = entryDate;
            waterEntry.SavedDate = savedDate;
            return waterEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Ounces
        {
            get
            {
                return _Ounces;
            }
            set
            {
                OnOuncesChanging(value);
                ReportPropertyChanging("Ounces");
                _Ounces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ounces");
                OnOuncesChanged();
            }
        }
        private global::System.Decimal _Ounces;
        partial void OnOuncesChanging(global::System.Decimal value);
        partial void OnOuncesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SavedDate
        {
            get
            {
                return _SavedDate;
            }
            set
            {
                OnSavedDateChanging(value);
                ReportPropertyChanging("SavedDate");
                _SavedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavedDate");
                OnSavedDateChanged();
            }
        }
        private global::System.DateTime _SavedDate;
        partial void OnSavedDateChanging(global::System.DateTime value);
        partial void OnSavedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DietJournal.Data.Entries", Name="WeightEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WeightEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WeightEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="entryDate">Initial value of the EntryDate property.</param>
        /// <param name="savedDate">Initial value of the SavedDate property.</param>
        public static WeightEntry CreateWeightEntry(global::System.Int32 id, global::System.Guid userId, global::System.Decimal amount, global::System.DateTime entryDate, global::System.DateTime savedDate)
        {
            WeightEntry weightEntry = new WeightEntry();
            weightEntry.Id = id;
            weightEntry.UserId = userId;
            weightEntry.Amount = amount;
            weightEntry.EntryDate = entryDate;
            weightEntry.SavedDate = savedDate;
            return weightEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SavedDate
        {
            get
            {
                return _SavedDate;
            }
            set
            {
                OnSavedDateChanging(value);
                ReportPropertyChanging("SavedDate");
                _SavedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavedDate");
                OnSavedDateChanged();
            }
        }
        private global::System.DateTime _SavedDate;
        partial void OnSavedDateChanging(global::System.DateTime value);
        partial void OnSavedDateChanged();

        #endregion
    
    }

    #endregion
    
}
